stages:
  - build
  - deploy

build_development:
  stage: build
  environment: development
  tags:
    - hrms
  before_script:
    - echo "prepare to build development"
    - pwd
  script:
    - python3 /home/gitlab-runner/deployment.py build web dev
    - echo "Build successful"
  only:
    refs:
      - develop
      - khanhnn17

deploy_to_development_environment:
  stage: deploy
  tags:
    - hrms
  before_script:
    - echo "prepare to deploy development"
    - pwd
  script:
    - python3 /home/gitlab-runner/deployment.py deploy web dev
    - echo "Deployed"
  when: manual
  only:
      - develop
      - khanhnn17
      
build_production:
  stage: build
  environment: development
  tags:
    - hrms-production
  script:
    - ls
    - python3 ~/deployment.py build web prod
    - echo "Build successful"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
    paths:
      - build/
    expire_in: 3 days
  only:
    refs:
      - master
      - feature/rollout
      
deploy_to_production_environment:
  stage: deploy
  environment: Production
  tags:
    - hrms-production
  script:
    - python3 ~/deployment.py deploy web prod
    - echo "Deployed"
  when: manual
  artifacts:
    expire_in: 1 hour
    paths:
      - public
  only:
      - master
      - feature/rollout
